In [1]:
# Import the NumPy library for numerical computations
import numpy as np

In [3]:
# Define three lists: one for goalkeeper names, one for their heights, and one for their weights
GKNames = ["Onana","Maignan","Ederson","Donnarumma"]
GKHeights = ["190","190","188","196"]
GKWeights = ["93","89","87","92"]

In [4]:
# Convert the list of goalkeeper names into a NumPy array and print it
print(np.array(GKNames))

['Onana' 'Maignan' 'Ederson' 'Donnarumma']


In [5]:
# Create a matrix combining the goalkeeper names, heights, and weights
GKMatrix = [GKNames,GKHeights,GKWeights]

In [6]:
# Convert the goalkeeper matrix into a NumPy array and print it
print(np.array(GKMatrix))

[['Onana' 'Maignan' 'Ederson' 'Donnarumma']
 ['190' '190' '188' '196']
 ['93' '89' '87' '92']]


In [7]:
# Demonstrate the use of the arange function to create a range of numbers
# Create an array with numbers from 0 to 11
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# Create a 3x11 array filled with zeros
np.zeros((3,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
# Create a 3x11 array filled with ones
np.ones((3,11))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
# Generate a 3x3 array of random numbers from a standard normal distribution
print(np.random.randn(3,3))

[[-0.81705026 -2.23339863  1.4949714 ]
 [ 0.42910086 -0.3943879  -0.33435202]
 [ 0.74650152 -0.82704702  1.06772977]]


In [11]:
# Generate a 3x3 array of random integers between 1 and 100
print(np.random.randint(1,100,(3,3)))

[[54 87 55]
 [11 10  1]
 [12 94 96]]


In [12]:
# Re-import NumPy and redefine the goalkeeper data with numerical values for heights and weights
import numpy as np
GKNames = ["Onana","Maignan","Ederson","Donnarumma"]
GKHeights = [190,190,188,196]
GKWeights = [93,89,87,92]

In [13]:
# Convert the list of goalkeeper heights into a NumPy array
GKHeights = np.array(GKHeights)

In [14]:
# Find the maximum height among the goalkeepers
GKHeights.max()

np.int64(196)

In [15]:
# Find the index of the goalkeeper with the maximum height
GKHeights.argmax()

np.int64(3)

In [16]:
# Retrieve the name of the tallest goalkeeper using the index
GKNames[GKHeights.argmax()]

'Donnarumma'