In [1]:
# Import the NumPy library for numerical operations
import numpy as np

In [2]:
# Create an array of World Cup years from 1930 to 2022, with a step of 4 years
WCYears = np.arange(1930,2023,4)

In [3]:
# Display the array of World Cup years
WCYears

array([1930, 1934, 1938, 1942, 1946, 1950, 1954, 1958, 1962, 1966, 1970,
       1974, 1978, 1982, 1986, 1990, 1994, 1998, 2002, 2006, 2010, 2014,
       2018, 2022])

In [4]:
# Remove the years 1942 and 1946 (index 3 and 4) as World Cups were not held during these years
WCYears = np.delete(WCYears,(3,4))

In [5]:
# Display the updated array of World Cup years
WCYears

array([1930, 1934, 1938, 1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978,
       1982, 1986, 1990, 1994, 1998, 2002, 2006, 2010, 2014, 2018, 2022])

In [6]:
# Demonstrate bracket selection for accessing specific elements in the array
# Find the year of the third World Cup (index 2 in the array)
WCYears[2]

np.int64(1938)

In [7]:
# Display the four World Cups held after World War II (indices 3 to 6)
WCYears[3:7]

array([1950, 1954, 1958, 1962])

In [8]:
# Demonstrate selection in a second array (grid) for more complex indexing
# Create arrays for World Cup years, hosts, and winners for recent tournaments
WCYears=[2002,2006,2010,2014]
WCHosts=["Korea/Japan","Germany","South Africa","Brazil"]
WCWinners=["Brazil","Italy","Spain","Germany"]

In [9]:
# Combine the arrays into a 2D NumPy array for easier indexing
WCArray = np.array((WCYears,WCHosts,WCWinners))

In [10]:
# Display the 2D array containing World Cup years, hosts, and winners
WCArray

array([['2002', '2006', '2010', '2014'],
       ['Korea/Japan', 'Germany', 'South Africa', 'Brazil'],
       ['Brazil', 'Italy', 'Spain', 'Germany']], dtype='<U21')

In [11]:
# Find the host of the 2010 World Cup (second row, third column)
WCArray[1,2]

np.str_('South Africa')

In [12]:
# Find the winner of the last World Cup in the array using negative indexing
WCArray[2,-1]

np.str_('Germany')

In [13]:
# Demonstrate selecting part of an array based on specific criteria
# Create arrays for World Cup years, top scorers, and their goal counts
WCYears=np.array([1966,1970,1974,1978])
WCTopScores=np.array(["Eusebio","Muller","Lato","Kempes"])
WCGoals=np.array([9,10,7,6])

In [14]:
# Identify which top scorers scored more than 8 goals
WCGoals > 8

array([ True,  True, False, False])

In [15]:
# Use bracket selection to find the names of top scorers who scored more than 8 goals
WCTopScores[(WCGoals>8)]

array(['Eusebio', 'Muller'], dtype='<U7')